version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.21
    container_name: webserver
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP Service
  php:
    build: ./.docker/php
    container_name: php
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php
    depends_on:
     mysql:
      condition: service_healthy


  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: demo
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10


  adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports:
      - 8080:8080
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy

# Volumes
volumes:

  mysqldata:
